name: pawprints
description: "Pawprint project"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2
  cloud_firestore: ^5.4.3
  intl: ^0.19.0
  flutter_toastr: ^1.0.3
  dynamic_color: ^1.7.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/img/paw_logo.png
    - lib/assets/img/pets_banner.jpg
